/// Flutter icons NewsIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewsIcon
///      fonts:
///       - asset: fonts/NewsIcon.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names, dangling_library_doc_comments

import 'package:flutter/widgets.dart';

class NewsIcon {
  NewsIcon._();

  static const _kFontFam = 'NewsIcon';
  static const String? _kFontPkg = null;

  static const IconData ant_design__file_jpg_outlined = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_icons__link_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_icons__verify_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bx__calendar_check = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bxs__file_pdf = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carbon__grid = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ci__calendar_check = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ep__video_play = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entypo__attachment = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData formkit__time = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heroicons__language_solid = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hugeicons__chat_bot = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__baseline_facebook = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f7__menu = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__baseline_telegram = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__outline_lock = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic__outline_notifications_off = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_park_outline__triangle_round_rectangle = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconamoon__search_light = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8__pdf = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData la__flag_usa = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lets_icons__video_light = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lets_icons__video = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lucide__tag = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mage__edit = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData majesticons__calendar_line = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__account_circle_outline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__database_outline = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__device_reset_rounded = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__download_2_outline_rounded = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__edit_square_outline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__info_outline = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__info = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__mail_outline = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__newsmode_outline = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__newsmode = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__password = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols__star_outline = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols_light__flowchart_outline = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__account_check_outline = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__account_cog_outline = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__bell_notification_outline = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_edit_outline = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_month_outline = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_range_outline = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_outline = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_text_outline = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_week_outline = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__cellphone = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__file_jpg_box = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__filter_variant_remove = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__gender_male_female = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__radio_tower = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__scale_balance = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__server_outline = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__sparkles_outline = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_light__tag = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mingcute__earth_2_line = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mingcute__earth_3_line = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mynaui__search = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData octicon__tasklist_24 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openmoji__flag_cambodia = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pajamas__earth = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prime__twitter = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ri__whatsapp_line = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solar__list_outline = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabler__calendar_event = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tabler__eye = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tdesign__chart_filled = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tdesign__chart = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vscode_icons__file_type_pdf2 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi__calendar_check_outline = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prime__calendar = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
